version: '3.1'

services:
  golang:
    build: ./
    image: yougo
    links:
      - db
    ports:
      - 8081:8081
    networks:
      - dockernet
    restart: always

  db:
    image: postgres
    restart: always
    networks:
      - dockernet
    volumes:
      - /tmp/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    links:
      - db
    networks:
      - dockernet
    ports:
      - 8080:8080

networks:
  dockernet:
    external: true